	;Models
	INCBIN "graphics/models/buildingthin.mdl"
	INCBIN "graphics/models/buildings4d.mdl"
	INCBIN "graphics/models/buildings3d.mdl"
	INCBIN "graphics/models/buildings4tall.mdl"
	INCBIN "graphics/models/buildingthinlogo.mdl"
	INCBIN "graphics/models/greatcommanderbossassembly.mdl"
	INCBIN "graphics/models/greatcommanderbosshead.mdl"
	INCBIN "graphics/models/greatcommanderbossmiddle.mdl"
	INCBIN "graphics/models/greatcommanderbossbottom.mdl"
	INCBIN "graphics/models/greatcommanderbossall.mdl"
	INCBIN "graphics/models/greatcommanderbossmidcenter.mdl"
	INCBIN "graphics/models/greatcommanderbossmidleft.mdl"
	INCBIN "graphics/models/greatcommanderbossmidright.mdl"
	INCBIN "graphics/models/greatcommanderbossweakleft.mdl"
	INCBIN "graphics/models/greatcommanderbossweakright.mdl"
	INCBIN "graphics/models/unknown_10A1F2.mdl"
	INCBIN "graphics/models/unknown_10A21F.mdl"
	INCBIN "graphics/models/unknown_10A24F.mdl"
	INCBIN "graphics/models/unknown_10A72D.mdl"
	INCBIN "graphics/models/bevbeam1.mdl"
	INCBIN "graphics/models/bevbeam2.mdl"
	INCBIN "graphics/models/bevbeam3.mdl"
	INCBIN "graphics/models/bevbeam4.mdl"
	INCBIN "graphics/models/bevbeam5.mdl"
	INCBIN "graphics/models/bevbeam6.mdl"
	INCBIN "graphics/models/bevbeam7.mdl"
	INCBIN "graphics/models/bevbeam8.mdl"
	INCBIN "graphics/models/risingarchway.mdl"
	INCBIN "graphics/models/cockpit.mdl"
	INCBIN "graphics/models/arwingnowings.mdl"
	INCBIN "graphics/models/arwingnoleftwing.mdl"
	INCBIN "graphics/models/arwingnorightwing.mdl"
	INCBIN "graphics/models/artsything.mdl"
	
	
