	;Models
	INCBIN "graphics/models/cyclopslegbroken.mdl"
	INCBIN "graphics/models/cyclopslegmissing.mdl"
	INCBIN "graphics/models/cyclopswalking.mdl"
	INCBIN "graphics/models/growingcolumn.mdl"
	INCBIN "graphics/models/bee.mdl"
	INCBIN "graphics/models/weirdantenna.mdl"
	INCBIN "graphics/models/unknown_0C8AF5.mdl"
	INCBIN "graphics/models/weirdantennatop.mdl"
	INCBIN "graphics/models/hexmissilehead.mdl"
	INCBIN "graphics/models/unknown_0C8D1E.mdl"
	INCBIN "graphics/models/slammingarrowwall.mdl"
	INCBIN "graphics/models/flatfarawayfourarmedenemy.mdl"
	INCBIN "graphics/models/pyramid.mdl"
	INCBIN "graphics/models/flatfarawayship.mdl"
	INCBIN "graphics/models/unknown_0C8F0D.mdl"
	INCBIN "graphics/models/unknown_0C8F76.mdl"
	INCBIN "graphics/models/unknown_0C8FA2.mdl"
	INCBIN "graphics/models/unknown_0C900B.mdl"
	INCBIN "graphics/models/caterpillarhead.mdl"
	INCBIN "graphics/models/caterpillarpart.mdl"
	INCBIN "graphics/models/unknown_0C919F.mdl"
	INCBIN "graphics/models/unknown_0C9228.mdl"
	INCBIN "graphics/models/cloakingship.mdl"
	INCBIN "graphics/models/unknown_0C93C9.mdl"
	INCBIN "graphics/models/unknown_0C94C7.mdl"
	INCBIN "graphics/models/caterpillar2part.mdl"
	INCBIN "graphics/models/caterpillar2head.mdl"
	INCBIN "graphics/models/octshadow.mdl"
	INCBIN "graphics/models/unknown_0C95F4.mdl"
	INCBIN "graphics/models/miniship.mdl"
	INCBIN "graphics/models/miniship2.mdl"
	INCBIN "graphics/models/miniship3.mdl"
	INCBIN "graphics/models/turret.mdl"
	INCBIN "graphics/models/tanktrack.mdl"
	INCBIN "graphics/models/tanktrackcorner.mdl"
	INCBIN "graphics/models/unknown_0C9B94.mdl"
	INCBIN "graphics/models/unknown_0C9BB0.mdl"
	INCBIN "graphics/models/unknown_0C9C32.mdl"
	INCBIN "graphics/models/launcherhovercraft.mdl"
	INCBIN "graphics/models/unknown_0C9DA6.mdl"
	INCBIN "graphics/models/unknown_0C9DF1.mdl"
	INCBIN "graphics/models/obelisk.mdl"
	INCBIN "graphics/models/unknown_0C9EC2.mdl"
	INCBIN "graphics/models/unknown_0C9EF2.mdl"
	INCBIN "graphics/models/midring.mdl"
	INCBIN "graphics/models/middoor.mdl"
	INCBIN "graphics/models/plasmahydrabossarms.mdl"
	INCBIN "graphics/models/plasmahydrabossarmsanimated.mdl"
	INCBIN "graphics/models/plasmahydrabossbody.mdl"
	INCBIN "graphics/models/plasmahydrabossclaw.mdl"
	INCBIN "graphics/models/monarchdodorabossnecktail.mdl"
	INCBIN "graphics/models/monarchdodorabosshead.mdl"
	INCBIN "graphics/models/monarchdodorabossbody.mdl"
	INCBIN "graphics/models/monarchdodorabosstailtip.mdl"
	INCBIN "graphics/models/monarchdodorabossbird.mdl"
	INCBIN "graphics/models/monarchdodorabossegg.mdl"
	INCBIN "graphics/models/monarchdodorabosseggtop.mdl"
	INCBIN "graphics/models/monarchdodorabosseggbottom.mdl"
	INCBIN "graphics/models/monarchdodorabosswingleft.mdl"
	INCBIN "graphics/models/monarchdodorabosswingright.mdl"
	INCBIN "graphics/models/unknown_0CBCFF.mdl"
	INCBIN "graphics/models/motorist.mdl"
	INCBIN "graphics/models/dart.mdl"
	INCBIN "graphics/models/bigbluebonusarchway.mdl"
	INCBIN "graphics/models/bigbluebonusverticaldoorway.mdl"
	INCBIN "graphics/models/slidingarrowdoor.mdl"
	INCBIN "graphics/models/unknown_0CC7A6.mdl"
	INCBIN "graphics/models/scrambletunnelwireframe.mdl"
	INCBIN "graphics/models/scramblearches.mdl"
	INCBIN "graphics/models/scrambletunnel.mdl"
	INCBIN "graphics/models/bigwalker.mdl"
	INCBIN "graphics/models/asteroidambush.mdl"
	INCBIN "graphics/models/vent.mdl"
	INCBIN "graphics/models/dancinginsectorbosshead.mdl"
	INCBIN "graphics/models/dancinginsectorbossleg.mdl"
	INCBIN "graphics/models/dancinginsectorbosshat.mdl"
	INCBIN "graphics/models/parrot.mdl"
	INCBIN "graphics/models/unknown_0CDFE1.mdl"
	INCBIN "graphics/models/highpolyarwing.mdl"
	INCBIN "graphics/models/lavaerupto.mdl"
	INCBIN "graphics/models/slotmachine.mdl"
	INCBIN "graphics/models/slotmachinearm.mdl"
	INCBIN "graphics/models/trainingring.mdl"
	INCBIN "graphics/models/androsselongatedbipyramid.mdl"
	INCBIN "graphics/models/towertop.mdl"
	INCBIN "graphics/models/ufo.mdl"
	INCBIN "graphics/models/smalltank.mdl"
	INCBIN "graphics/models/tunnelwithdoorleft.mdl"
	INCBIN "graphics/models/tunnelwithdoorright.mdl"
	INCBIN "graphics/models/bonusdoors.mdl"
	INCBIN "graphics/models/lettere.mdl"
	INCBIN "graphics/models/lettert.mdl"
	INCBIN "graphics/models/lettern.mdl"
	INCBIN "graphics/models/letterh.mdl"
	
	;Transfer $00F0 bytes to SPC address $3D00
	DW $00F0,$3D00
	;Data to transfer
	DB $00,$FF,$E0,$B8,$03,$40,$01,$FF,$E0,$B8,$03,$10,$02,$FF,$E0,$B8
	DB $02,$B0,$03,$FF,$E0,$B8,$02,$F0,$04,$FF,$E0,$B8,$06,$40,$05,$FF
	DB $E0,$B8,$06,$B0,$06,$FF,$E0,$B8,$03,$B0,$07,$FF,$E0,$B8,$02,$00
	DB $08,$FF,$E0,$B8,$02,$00,$09,$FF,$E0,$B8,$04,$70,$0A,$FF,$E0,$B8
	DB $00,$80,$0B,$FF,$E0,$B8,$03,$C0,$0C,$FF,$E0,$B8,$07,$A0,$0D,$FF
	DB $E0,$B8,$03,$D0,$0E,$FF,$E0,$B8,$05,$B0,$0F,$FF,$E0,$B8,$07,$A0
	DB $10,$FF,$E0,$B8,$07,$A0,$11,$FF,$EC,$B8,$02,$A0,$12,$FF,$E0,$B8
	DB $07,$A0,$13,$FF,$E0,$B8,$03,$C0,$14,$DF,$34,$B8,$02,$00,$15,$F6
	DB $F1,$B8,$02,$00,$16,$FF,$EE,$B8,$02,$00,$17,$FF,$E0,$B8,$05,$B0
	DB $18,$FF,$E0,$B8,$03,$00,$19,$FF,$E0,$B8,$03,$00,$1A,$FF,$E0,$B8
	DB $04,$90,$1B,$FF,$E0,$B8,$07,$A0,$1C,$FF,$ED,$B8,$03,$00,$1D,$FF
	DB $F0,$B8,$03,$00,$1E,$FF,$F6,$B8,$03,$00,$1F,$FF,$E0,$B8,$03,$00
	DB $20,$FE,$E0,$B8,$03,$A0,$21,$FF,$ED,$B8,$03,$C0,$22,$FF,$F3,$B8
	DB $03,$C0,$23,$FF,$F6,$B8,$03,$C0,$24,$FF,$E0,$B8,$03,$C0,$25,$FF
	DB $E0,$B8,$03,$C0,$26,$FF,$E0,$B8,$03,$00,$27,$FF,$E0,$B8,$01,$00
	;Transfer $0458 bytes to SPC address $E000
	DW $0458,$E000
	;Data to transfer
	;Music data
	INCBIN "audio/songs/intro.mus"
	;Transfer $0004 bytes to SPC address $FDC8
	DW $0004,$FDE2
	;Data to transfer
	;Music pointers
	DW $E000,$E000
	;End of transfer
	DW $0000,$0400
