	;Compressed graphics assets
	INCBIN "graphics/compressed/corneria.mapz"
	INCBIN "graphics/compressed/sectorx.4bpp.chrz"
	INCBIN "graphics/compressed/titania.4bpp.chrz"
	INCBIN "graphics/compressed/titaniabossbg.4bpp.chrz"
	INCBIN "graphics/compressed/asteroid1.4bpp.chrz"
	INCBIN "graphics/compressed/atomicbase.4bpp.chrz"
	INCBIN "graphics/compressed/spacearmada.4bpp.chrz"
	INCBIN "graphics/compressed/venomboss.mapz"
	INCBIN "graphics/compressed/asteroid3.4bpp.chrz"
	INCBIN "graphics/compressed/highwaybg.4bpp.chrz"
	INCBIN "graphics/compressed/stageselect.4bpp.chrz"
	INCBIN "graphics/compressed/fortuna.4bpp.chrz"
	INCBIN "graphics/compressed/highwaybg.mapz"
	INCBIN "graphics/compressed/highwayroad.mapz"
	INCBIN "graphics/compressed/sectorz.4bpp.chrz"
