	;Additional level scripts
	INCBIN "levels/scramble.bin"
	INCBIN "levels/init_players.bin"
	INCBIN "levels/corneria2_main.bin"
	INCBIN "levels/corneria1_main.bin"
	INCBIN "levels/sectorx_main.bin"
	INCBIN "levels/asteroid1_main.bin"
	INCBIN "levels/spacearmada_main_b.bin"
	INCBIN "levels/spacearmada_main_c.bin"
	INCBIN "levels/spacearmada_main_d.bin"
	INCBIN "levels/spacearmada_main_e.bin"
	INCBIN "levels/spacearmada_main_f.bin"
	INCBIN "levels/spacearmada_main_g.bin"
	INCBIN "levels/spacearmada_boss.bin"
	INCBIN "levels/meteor_main.bin"
	INCBIN "levels/unknown_0DBB77.bin"
	INCBIN "levels/venom1_main.bin"
	;Main level scripts
	INCBIN "levels/blackhole.bin"
	INCBIN "levels/outofthisdimension.bin"
	;Additional level scripts
	INCBIN "levels/outofthisdimension_main.bin"
	INCBIN "levels/unknown_0DCB4D.bin"
	INCBIN "levels/venom_end.bin"
	INCBIN "levels/corneria_end.bin"
	;Main level scripts
	INCBIN "levels/corneria1.bin"
	INCBIN "levels/asteroid1.bin"
	INCBIN "levels/spacearmada.bin"
	INCBIN "levels/meteor.bin"
	INCBIN "levels/venom1atmosphere.bin"
	INCBIN "levels/venom1.bin"
	;Additional level script
	INCBIN "levels/venom_boss.bin"
	;Main level scripts
	INCBIN "levels/corneria2.bin"
	INCBIN "levels/sectorx.bin"
	INCBIN "levels/titania.bin"
	INCBIN "levels/sectory.bin"
	INCBIN "levels/venom2atmosphere.bin"
	INCBIN "levels/highway.bin"
	INCBIN "levels/corneria3.bin"
	INCBIN "levels/asteroid3.bin"
	INCBIN "levels/fortuna.bin"
	INCBIN "levels/sectorz.bin"
	INCBIN "levels/macbeth.bin"
	INCBIN "levels/venom3atmosphere.bin"
	INCBIN "levels/venom3.bin"
	INCBIN "levels/unknown_0DE889.bin"
	INCBIN "levels/sectory_end.bin"
	INCBIN "levels/unknown_0DEA31.bin"
	INCBIN "levels/titania_end.bin"
	INCBIN "levels/spacearmada_main_a.bin"
	INCBIN "levels/blackhole_main.bin"
	INCBIN "levels/training.bin"
	INCBIN "levels/ending.bin"
	INCBIN "levels/ending_main_a.bin"
	INCBIN "levels/ending_main_b.bin"
	INCBIN "levels/intro.bin"
	INCBIN "levels/title.bin"
	INCBIN "levels/controls.bin"
	;Compressed tiles
	INCBIN "graphics/compressed/unk0DFBB9.binz"		;char (00FF96)
