	;Additional level scripts
	INCBIN "levels/scramble.lev"
	INCBIN "levels/init_players.lev"
	INCBIN "levels/corneria2_main.lev"
	INCBIN "levels/corneria1_main.lev"
	INCBIN "levels/sectorx_main.lev"
	INCBIN "levels/asteroid1_main.lev"
	INCBIN "levels/spacearmada_main_b.lev"
	INCBIN "levels/spacearmada_main_c.lev"
	INCBIN "levels/spacearmada_main_d.lev"
	INCBIN "levels/spacearmada_main_e.lev"
	INCBIN "levels/spacearmada_main_f.lev"
	INCBIN "levels/spacearmada_main_g.lev"
	INCBIN "levels/spacearmada_boss.lev"
	INCBIN "levels/meteor_main.lev"
	INCBIN "levels/unknown_0DBB77.lev"
	INCBIN "levels/venom1_main.lev"
	;Main level scripts
	INCBIN "levels/blackhole.lev"
	INCBIN "levels/outofthisdimension.lev"
	;Additional level scripts
	INCBIN "levels/outofthisdimension_main.lev"
	INCBIN "levels/unknown_0DCB4D.lev"
	INCBIN "levels/venom_end.lev"
	INCBIN "levels/corneria_end.lev"
	;Main level scripts
	INCBIN "levels/corneria1.lev"
	INCBIN "levels/asteroid1.lev"
	INCBIN "levels/spacearmada.lev"
	INCBIN "levels/meteor.lev"
	INCBIN "levels/venom1atmosphere.lev"
	INCBIN "levels/venom1.lev"
	;Additional level script
	INCBIN "levels/venom_boss.lev"
	;Main level scripts
	INCBIN "levels/corneria2.lev"
	INCBIN "levels/sectorx.lev"
	INCBIN "levels/titania.lev"
	INCBIN "levels/sectory.lev"
	INCBIN "levels/venom2atmosphere.lev"
	INCBIN "levels/highway.lev"
	INCBIN "levels/corneria3.lev"
	INCBIN "levels/asteroid3.lev"
	INCBIN "levels/fortuna.lev"
	INCBIN "levels/sectorz.lev"
	INCBIN "levels/macbeth.lev"
	INCBIN "levels/venom3atmosphere.lev"
	INCBIN "levels/venom3.lev"
	INCBIN "levels/unknown_0DE889.lev"
	INCBIN "levels/sectory_end.lev"
	INCBIN "levels/unknown_0DEA31.lev"
	INCBIN "levels/titania_end.lev"
	INCBIN "levels/spacearmada_main_a.lev"
	INCBIN "levels/blackhole_main.lev"
	INCBIN "levels/training.lev"
	INCBIN "levels/ending.lev"
	INCBIN "levels/ending_main_a.lev"
	INCBIN "levels/ending_main_b.lev"
	INCBIN "levels/intro.lev"
	INCBIN "levels/title.lev"
	INCBIN "levels/controls.lev"
	;Compressed tiles
	INCBIN "graphics/compressed/venombosstunnel.4bpp.chrz"

	; 0DFBB9	5C00		1800
